version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  reviewers:
    - "jxsl13"

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  reviewers:
    - "jxsl13"